#git add .;git commit -m "all";git push origin main
networks:
  roboshop:
    driver: bridge
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  web:
    image: vamsi0122/web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - 80:80
  
  catalogue:
    image: vamsi0122/catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  mongodb:
    image: vamsi0122/mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - source: mongodb
        target: /data/db
        type: volume
  