#git add .;git commit -m "all";git push origin main
networks:
  roboshop:
    driver: bridge

services:
  web:
    image: vamsi0122/web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - 80:80
